/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio.vista;


import java.awt.Desktop;
import colegio.controlador.clsAsignaciones;
import colegio.modelo.daoAsigna;
import colegio.*;
import colegio.controlador.clsAulas;
import colegio.controlador.clsCarreras;
import colegio.controlador.clsCursos;
import colegio.controlador.clsSedes;
import colegio.modelo.daoAula;
import colegio.modelo.daoCarrera;
import colegio.modelo.daoCurso;
import colegio.modelo.daoSede;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmMantenimientoAsignacion extends javax.swing.JInternalFrame {


 


    public void llenadoDeCombosAula() {
        daoAula cargoDAO = new daoAula();
        List<clsAulas> cargos = cargoDAO.select();
        cbox_aula.addItem("Seleccione un cargo");
        for (int i = 0; i < cargos.size(); i++) {
            cbox_aula.addItem(cargos.get(i).getnombre_aula());
        }
    }
     public void llenadoDeCombosSede() {
        daoSede cargoDAO = new daoSede();
        List<clsSedes> cargos = cargoDAO.select();
        cbox_sede.addItem("Seleccione un cargo");
        for (int i = 0; i < cargos.size(); i++) {
            cbox_sede.addItem(cargos.get(i).getnombre_sede());
        }
    }
       public void llenadoDeCombosCarrera() {
        daoCarrera cargoDAO = new daoCarrera();
        List<clsCarreras> cargos = cargoDAO.select();
        cbox_carrera.addItem("Seleccione un cargo");
        for (int i = 0; i < cargos.size(); i++) {
            cbox_carrera.addItem(cargos.get(i).getnombre_carrera());
        }
    }
    
 

    public void llenadoDeCombosCurso() {
        daoCurso departamentoDAO = new daoCurso();
        List<clsCursos> departamentos = departamentoDAO.select();
        cbox_curso.addItem("Seleccione un departamento");
        for (int i = 0; i < departamentos.size(); i++) {
            cbox_curso.addItem(departamentos.get(i).getnombre_curso());
        }
    }
    
 
    
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id asignacion");
        modelo.addColumn("Nombre");
        modelo.addColumn("Sede");
        modelo.addColumn("Aula");
        modelo.addColumn("Curso");
     
        daoAsigna asignacionDAO = new daoAsigna();
        List<clsAsignaciones> asignaciones = asignacionDAO.select();
        tablaEmpleados.setModel(modelo);
        String[] dato = new String[5];
        for (int i = 0; i < asignaciones.size(); i++) {
            dato[0] = Integer.toString(asignaciones.get(i).getcodigo_asignacion());
            dato[1] = asignaciones.get(i).getnombre_carrera();
            dato[2] = asignaciones.get(i).getnombre_sede();
            dato[3] = asignaciones.get(i).getnombre_aula();
            dato[4] = asignaciones.get(i).getnombre_curso();
           
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarEmpleados() {
        clsAsignaciones asignacionAConsultar = new clsAsignaciones();
        daoAsigna asignacionDAO = new daoAsigna();
        asignacionAConsultar.setcodigo_asignacion(Integer.parseInt(txtbuscado.getText()));
        asignacionAConsultar = asignacionDAO.query(asignacionAConsultar);
       cbox_aula.setSelectedItem(asignacionAConsultar.getnombre_aula());
        cbox_sede.setSelectedItem(asignacionAConsultar.getnombre_sede());
        cbox_carrera.setSelectedItem(asignacionAConsultar.getnombre_carrera());
        cbox_curso.setSelectedItem(asignacionAConsultar.getnombre_curso());
      
    }

    public frmMantenimientoAsignacion() {
        initComponents();
        llenadoDeTablas();
        llenadoDeCombosAula();
        llenadoDeCombosCurso();
        llenadoDeCombosSede();
                llenadoDeCombosCarrera();
      
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        cbox_carrera = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        cbox_curso = new javax.swing.JComboBox<>();
        label7 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        cbox_sede = new javax.swing.JComboBox<>();
        cbox_aula = new javax.swing.JComboBox<>();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento asignacion");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 95, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 95, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 95, -1));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label1.setText("Datos");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 95, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 95, -1));

        tablaEmpleados.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id empleado", "Nombre", "Salario", "Estado", "Horas Extras", "Cargo", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);
        if (tablaEmpleados.getColumnModel().getColumnCount() > 0) {
            tablaEmpleados.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 680, 330));

        cbox_carrera.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_carreraActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, -1));

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 100, -1));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, -1, -1));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label9.setText("Nombre Sede");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        label11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label6.setText("Nombre Aula");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        label13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label13.setText(".");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 450, 20, -1));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("-----------------Ingreso de datos -----------------");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, -1));

        cbox_curso.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_cursoActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 150, -1));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label7.setText("Nombre Curso");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label10.setText("Nombre Carrera");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 102, -1));

        cbox_sede.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_sedeActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, -1));

        cbox_aula.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_aulaActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int i =JOptionPane.showConfirmDialog(this, "seguro que quieres borrar este dato ");
        if ( i == 0){
        daoAsigna asignacionDAO = new daoAsigna();
        clsAsignaciones asignacionAEliminar = new clsAsignaciones();
        asignacionAEliminar.setcodigo_asignacion(Integer.parseInt(txtbuscado.getText()));
        asignacionDAO.delete(asignacionAEliminar);
        
         } else if(1==1){
         JOptionPane.showMessageDialog(this, "no se a borrado los datos ");
        }
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       
     
        daoAsigna asignacionDAO = new daoAsigna();
        clsAsignaciones asignacionAInsertar = new clsAsignaciones();
           asignacionAInsertar.setnombre_carrera(cbox_carrera.getSelectedItem().toString());
        asignacionAInsertar.setnombre_sede(cbox_sede.getSelectedItem().toString());
        asignacionAInsertar.setnombre_aula(cbox_aula.getSelectedItem().toString());
         asignacionAInsertar.setnombre_curso(cbox_curso.getSelectedItem().toString());
        asignacionDAO.insert(asignacionAInsertar);
        llenadoDeTablas();
    
        
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarEmpleados();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
//        // TODO add your handling code here:
int i =JOptionPane.showConfirmDialog(this, "seguro que quieres modificar este dato ");
        if ( i == 0){
        daoAsigna asignacionDAO = new daoAsigna();
        clsAsignaciones asignacionAActualizar = new clsAsignaciones();
        asignacionAActualizar.setcodigo_asignacion(Integer.parseInt(txtbuscado.getText()));
      asignacionAActualizar.setnombre_aula(cbox_aula.getSelectedItem().toString());
        asignacionAActualizar.setnombre_sede(cbox_sede.getSelectedItem().toString());
        asignacionAActualizar.setnombre_carrera(cbox_carrera.getSelectedItem().toString());
        asignacionAActualizar.setnombre_curso(cbox_curso.getSelectedItem().toString());
        asignacionDAO.update(asignacionAActualizar);
        }   else if(1==1){
         JOptionPane.showMessageDialog(this, "no se a modificado los datos ");
        }
        llenadoDeTablas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cbox_carrera.setSelectedIndex(0);
   
        cbox_curso.setSelectedIndex(0);
          cbox_sede.setSelectedIndex(0);
   
        cbox_aula.setSelectedIndex(0);
       
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbox_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_carreraActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_carreraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try{
            
            Desktop.getDesktop().browse(new URI("https://drive.google.com/file/d/1B1vJyre5vz7w_Wo9AK7Sa3UPGxhEm33y/view?usp=sharing"));
        } catch (Exception e){
JOptionPane.showMessageDialog(null, "No se puede abrir el archivo de ayuda, probablemente fue borrado","ERROR",JOptionPane.ERROR_MESSAGE);
 

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbox_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_cursoActionPerformed

    private void cbox_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_sedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_sedeActionPerformed

    private void cbox_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_aulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_aulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbox_aula;
    private javax.swing.JComboBox<String> cbox_carrera;
    private javax.swing.JComboBox<String> cbox_curso;
    private javax.swing.JComboBox<String> cbox_sede;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
